import type { CoupleTypeInfo } from './types';

/**
 * 异性恋情侣类型库（30 常见 + 5 稀有 = 35 种）
 * 来源：docs/COUPLE_TYPES.md v2.1
 * 雷达图数值映射：极高 90 / 高 75 / 中高 65 / 中 50 / 中低 35 / 低 20 / 极低 10 / 未提及默认 50
 * estimatedRatio 已归一化到组内总和 100%（2026-07-04 审查修复 W-WC-3）
 */
export const HETERO_COUPLE_TYPES: CoupleTypeInfo[] = [
  // ==================== 30 种常见类型 ====================

  // 1 · 烟火余生型
  {
    id: 'OLD_COUPLE',
    code: 'OLD_COUPLE',
    name: '烟火余生型',
    emoji: '🎆',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.1104,
    oneLiner: '我们的浪漫不是烛光晚餐，是知道对方鞋子放哪只脚',
    description: '双方都安全型依恋，冲突后能快速修复，关系进入稳定期。你们可能不再每天说「我爱你」，但一个眼神对方就懂。你们的危险不是分手，是「无聊」—— 需要主动制造新鲜感。',
    hiddenRisks: '容易把对方当「理所当然」；3 年后可能进入「室友感」',
    growthAdvice: '每周一次「新鲜事分享」；每季度一次「关系复盘」',
    shareCopy: '烟火余生型，激情退去后的温暖余温 🎆 测测你们是哪种',
    radarProfile: { D1: 75, D2: 75, D3: 75, D4: 75, D5: 75, D6: 75 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: true,
  },

  // 2 · 双螺旋型
  {
    id: 'DOUBLE_HELIX',
    code: 'DOUBLE_HELIX',
    name: '双螺旋型',
    emoji: '🧬',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0859,
    oneLiner: '我们都害怕对方不爱自己，所以拼命证明',
    description: '双方都焦虑型依恋，互相需要持续确认。吵架时两人都越说越激动，谁也不肯先停。你们的爱很浓烈，但也很消耗——因为你们都在用对方的反应来证明自己被爱。',
    hiddenRisks: '情绪过载时易说出伤害对方的话；3 年后容易累',
    growthAdvice: '学会「20 分钟冷静法」；建立「安全词」机制',
    shareCopy: '双螺旋型，焦虑基因互相缠绕 🧬 测测你们呢',
    radarProfile: { D1: 50, D2: 20, D3: 50, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'A×A',
    conflictPattern: 'pursue-pursue',
    stage: 'adjustment',
    isPublic: true,
  },

  // 3 · 风筝与线型
  {
    id: 'KITE_LINE',
    code: 'KITE_LINE',
    name: '风筝与线型',
    emoji: '🪁',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0736,
    oneLiner: '我越追你越跑，你越跑我越慌',
    description: 'EFT 经典「追-逃循环」—— 一方焦虑追逐确认，一方回避退缩自保。这是情侣咨询中最常见的组合，**也是最容易改善的**——一旦看懂这个循环，关系质量能快速提升。',
    hiddenRisks: '长期循环会让追逐方耗尽、回避方窒息，最终爆发性分手',
    growthAdvice: '追逐方练习「自我安抚」；回避方练习「先回应再退避」',
    shareCopy: '风筝与线型，我追你跑 🪁 测测你们的真相',
    radarProfile: { D1: 50, D2: 20, D3: 20, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'A×D',
    conflictPattern: 'pursue-withdraw',
    stage: 'adjustment',
    isPublic: true,
  },

  // 4 · 猫与激光笔型
  {
    id: 'CAT_LASER',
    code: 'CAT_LASER',
    name: '猫与激光笔型',
    emoji: '🐱',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0491,
    oneLiner: '我越躲你越追，你越追我越想躲',
    description: '风筝与线的镜像版本，**主导方不同**——回避方先启动循环。修复关键：回避方要先承认「我需要空间」而不是「我不在乎你」。',
    hiddenRisks: '回避方常被贴「渣」标签，其实是依恋策略不是不爱',
    growthAdvice: '回避方练习说「我需要 30 分钟，不是你的错」',
    shareCopy: '猫与激光笔型，原来他不是渣 🐱 测测你们',
    radarProfile: { D1: 50, D2: 20, D3: 20, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'D×A',
    conflictPattern: 'withdraw-pursue',
    stage: 'adjustment',
    isPublic: true,
  },

  // 5 · 新酒未醒型
  {
    id: 'NEW_WINE',
    code: 'NEW_WINE',
    name: '新酒未醒型',
    emoji: '🍷',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0613,
    oneLiner: '我们还没吵过架，但愿永远不吵',
    description: '你们处于 Sternberg 爱情三角的「激情期」，荷尔蒙让一切都很美。但**真实关系还没开始**——蜜月期结束（平均 18 个月）后才是关系的真正考验。建议现在就建立冲突应对机制。',
    hiddenRisks: '容易把激情当爱情；危机来临时没有「冲突肌肉」',
    growthAdvice: '主动讨论「如果我们吵架了怎么办」；建立「修复尝试」暗号',
    shareCopy: '新酒未醒型，蜜月期还能撑 N 天 🍷 测测你们在哪个阶段',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 75, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'honeymoon',
    isPublic: true,
  },

  // 6 · 双子星型
  {
    id: 'TWIN_STAR',
    code: 'TWIN_STAR',
    name: '双子星型',
    emoji: '♊',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0429,
    oneLiner: '我们住在同一个屋檐下，但活在两个世界里',
    description: '双方都回避型依恋，互相给空间，但也互相不深入。表面和谐，实际是「情感休眠」。这种关系**最稳定也最危险**——稳定是因为没冲突，危险是因为一旦危机来临，没有情感储备可调用。',
    hiddenRisks: '关系温度持续走低；任一方遇到外部刺激易崩塌',
    growthAdvice: '每周一次「深度对话夜」；从分享小情绪开始重建亲密',
    shareCopy: '双子星型，各自运转互不干扰 ♊ 需要重新连上 WiFi',
    radarProfile: { D1: 50, D2: 75, D3: 50, D4: 20, D5: 50, D6: 50 },
    attachmentCombo: 'D×D',
    conflictPattern: 'withdraw-withdraw',
    stage: 'stable',
    isPublic: true,
  },

  // 7 · 战友背靠背型
  {
    id: 'COMRADE_BACK_TO_BACK',
    code: 'COMRADE_BACK_TO_BACK',
    name: '战友背靠背型',
    emoji: '⚔️',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0368,
    oneLiner: '我们的爱情，一半在床上，一半在 PPT 里',
    description: '你们是「战友型情侣」—— 一起打拼、互相支持事业。优势是共同意义强，风险是把关系变成了「合伙人」，忘了浪漫。',
    hiddenRisks: '亲密激情维度低；浪漫仪式感缺失',
    growthAdvice: '每月一次「不聊工作的约会」；保留 1 个纯恋爱话题',
    shareCopy: '战友背靠背型，一半浪漫一半 PPT ⚔️',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 75, D6: 35 },
    attachmentCombo: 'S/D×S/D',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: true,
  },

  // 8 · 灯塔与舟型
  {
    id: 'LIGHTHOUSE_BOAT',
    code: 'LIGHTHOUSE_BOAT',
    name: '灯塔与舟型',
    emoji: '🔦',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0245,
    oneLiner: '他/她不只是爱人，是我成长路上的人',
    description: '一方明显是另一方的「精神引路人」，常见于年龄差或阅历差较大的关系。优势是成长快，风险是权力不对等，被引导方可能逐渐失去自我。',
    hiddenRisks: '被引导方依赖过重；引导方易疲惫',
    growthAdvice: '被引导方独立做 3 个决定；引导方练习「不指点」',
    shareCopy: '灯塔与舟型，我爱的人也是引路人 🔦',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 50, D6: 50 },
    attachmentCombo: 'S×A/F',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: true,
  },

  // 9 · 渡人与舟型
  {
    id: 'FERRY_BOAT',
    code: 'FERRY_BOAT',
    name: '渡人与舟型',
    emoji: '🛶',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '在我最差的时候，你接住了我',
    description: '一方在低谷期被另一方「救起」，关系建立在「感恩」之上。优势是情感羁绊深，风险是「救命之恩」不等同于爱情，感恩耗尽后关系易失衡。',
    hiddenRisks: '一方长期扮演「拯救者」角色，压抑自身需求',
    growthAdvice: '拯救方说出 3 件「我也需要你」的事；被救方独立解决 1 个难题',
    shareCopy: '渡人与舟型，你接住了最差的我 🛶',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 50, D5: 75, D6: 50 },
    attachmentCombo: 'A/F×S',
    conflictPattern: 'pursue-withdraw',
    stage: 'stable',
    isPublic: true,
  },

  // 10 · 双生藤蔓型
  {
    id: 'TWIN_VINE',
    code: 'TWIN_VINE',
    name: '双生藤蔓型',
    emoji: '🌿',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0307,
    oneLiner: '我们不是找到了对方，是和对方一起成为了更好的人',
    description: '双方都有清晰的自我成长方向，关系是「加分项」不是「依赖项」。这是最健康的关系形态之一，**也是 Paired 等产品想推用户达到的终极目标**。',
    hiddenRisks: '容易过度理性，忽略感性需求',
    growthAdvice: '每周一次「纯感性对话」；允许自己「不成长」的一天',
    shareCopy: '双生藤蔓型，我们是彼此的加分项 🌿',
    radarProfile: { D1: 75, D2: 75, D3: 75, D4: 75, D5: 75, D6: 75 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: true,
  },

  // 11 · 火星撞地球型
  {
    id: 'MARS_EARTH',
    code: 'MARS_EARTH',
    name: '火星撞地球型',
    emoji: '💥',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0245,
    oneLiner: '我们吵得邻居都搬走了，但还爱着',
    description: '双方都情绪化，冲突激烈但修复也快。这是「火花型」关系——爱得浓烈吵得也凶。Sternberg 称之为「激情主导型」，缺乏承诺和亲密的稳固基础。',
    hiddenRisks: '长期情绪过载，3-5 年后易崩盘',
    growthAdvice: '建立「吵架红线」（不摔门/不拉黑/不过夜）；每月复盘一次',
    shareCopy: '火星撞地球型，邻居都搬走了 💥 测测你们',
    radarProfile: { D1: 20, D2: 10, D3: 75, D4: 50, D5: 50, D6: 75 },
    attachmentCombo: 'A×F',
    conflictPattern: 'pursue-pursue',
    stage: 'crisis',
    isPublic: true,
  },

  // 12 · 老井深泉型
  {
    id: 'OLD_WELL',
    code: 'OLD_WELL',
    name: '老井深泉型',
    emoji: '🪣',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我们都不太会吵架，也就没什么大事',
    description: '一方回避一方安全，关系温度低但稳定。常见于「相亲-结婚」式关系，**功能性强但情感浓度低**。',
    hiddenRisks: '关系温度持续低；任一方遇情感诱惑易动摇',
    growthAdvice: '每周一次「情绪分享」；建立「深度对话」习惯',
    shareCopy: '老井深泉型，不喧哗但不会干涸 🪣',
    radarProfile: { D1: 60, D2: 60, D3: 60, D4: 60, D5: 60, D6: 60 },
    attachmentCombo: 'D×S',
    conflictPattern: 'withdraw-pursue',
    stage: 'stable',
    isPublic: true,
  },

  // 13 · 候鸟迁徙型
  {
    id: 'MIGRATORY_BIRD',
    code: 'MIGRATORY_BIRD',
    name: '候鸟迁徙型',
    emoji: '✈️',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0307,
    oneLiner: '我们的爱情，一半在视频里，一半在机票里',
    description: '异地恋是「阶段型特殊状态」，本身不是问题，问题是缺乏「结束异地的时间表」。**异地恋成功率与「是否有明确结束时间」强相关**。',
    hiddenRisks: '缺乏身体接触；信任消耗快',
    growthAdvice: '设定异地结束日期；每月一次见面；每日 5 分钟视频',
    shareCopy: '候鸟迁徙型，机票攒了一摞 ✈️',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 50, D5: 75, D6: 20 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: true,
  },

  // 14 · 沙漏倒计时型
  {
    id: 'HOURGLASS',
    code: 'HOURGLASS',
    name: '沙漏倒计时型',
    emoji: '⏳',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0245,
    oneLiner: '我们什么都好，就是卡在『下一步』',
    description: '一方急着推进关系（订婚/结婚/生子），一方还在犹豫。这是 25-32 岁情侣最高频的危机模式。**关键不是逼对方做决定，是搞清楚对方犹豫的真实原因**。',
    hiddenRisks: '长期拖延会消耗追逐方耐心；最终爆发性分手',
    growthAdvice: '设定「3 个月决策期」；列出「不结婚的 5 个真实理由」',
    shareCopy: '沙漏倒计时型，卡在『下一步』⏳',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 10, D5: 50, D6: 50 },
    attachmentCombo: 'A×S',
    conflictPattern: 'pursue-withdraw',
    stage: 'adjustment',
    isPublic: true,
  },

  // 15 · 围城内外型
  {
    id: 'SIEGE_CASTLE',
    code: 'SIEGE_CASTLE',
    name: '围城内外型',
    emoji: '🏰',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我们的爱情，第三个主角是爸妈',
    description: '双方父母对关系有强烈意见（反对/控制/挑刺），情侣需要共同应对外部压力。这种关系的**关键不是和父母斗，是和伴侣达成统一战线**。',
    hiddenRisks: '长期外部压力会内化为内部矛盾',
    growthAdvice: '建立「我们 vs 问题」框架；明确各自父母边界',
    shareCopy: '围城内外型，爱情第三个主角是爸妈 🏰',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 20, D5: 75, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'pursue-pursue',
    stage: 'crisis',
    isPublic: true,
  },

  // 16 · 破镜重圆型
  {
    id: 'BROKEN_MIRROR',
    code: 'BROKEN_MIRROR',
    name: '破镜重圆型',
    emoji: '🔄',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我们分过，又回来了',
    description: '分手后复合的情侣，处于「重生期」。**复合成功率取决于分手原因是否解决**——如果只是寂寞复合，复发率 > 70%；如果是问题解决后复合，成功率反而高于普通情侣。',
    hiddenRisks: '旧问题易复发；信任需要重建',
    growthAdvice: '写下「这次不同的 3 个具体改变」；每月检查 1 次',
    shareCopy: '破镜重圆型，分过又回来了 🔄',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 50, D5: 20, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'rebirth',
    isPublic: true,
  },

  // 17 · 陈年老酒型
  {
    id: 'AGED_WINE',
    code: 'AGED_WINE',
    name: '陈年老酒型',
    emoji: '🍶',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我们什么都好，就是不再心动',
    description: '在一起 5-8 年的情侣最高频状态，关系进入「平淡期」。Sternberg 称之为「空爱」—— 有承诺无激情。**关键不是分手，是重新激活激情**。',
    hiddenRisks: '任一方遇新刺激易出轨；长期空转消耗承诺',
    growthAdvice: '每月一次「重新认识对方」约会；尝试共同新挑战',
    shareCopy: '陈年老酒型，需要重新开封 🍶',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 50, D6: 20 },
    attachmentCombo: 'S×S',
    conflictPattern: 'withdraw-withdraw',
    stage: 'crisis',
    isPublic: true,
  },

  // 18 · 天平倾斜型
  {
    id: 'TILTED_SCALE',
    code: 'TILTED_SCALE',
    name: '天平倾斜型',
    emoji: '⚖️',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0245,
    oneLiner: '我付出 80%，你付出 20%，我们还说是 50/50',
    description: '关系投入严重不对称——一方承担大部分情感/家务/规划劳动。**这不是爱的问题，是边界问题**。修复关键是让低投入方「看见」高投入方的劳动。',
    hiddenRisks: '高投入方长期压抑易爆发；低投入方习以为常',
    growthAdvice: '列「家务/情感劳动清单」；低投入方接管 3 项',
    shareCopy: '天平倾斜型，是时候重新分账了 ⚖️',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'A×D',
    conflictPattern: 'pursue-withdraw',
    stage: 'crisis',
    isPublic: true,
  },

  // 19 · 云同桌型
  {
    id: 'CLOUD_DESKMATE',
    code: 'CLOUD_DESKMATE',
    name: '云同桌型',
    emoji: '☁️',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我们的关系，主要靠吃喝玩乐维系',
    description: '你们在一起很快乐，但从未讨论过沉重话题（未来/价值观/家庭）。**这是「功能性浅关系」**——稳定但缺乏深度，遇到真考验易碎。',
    hiddenRisks: '缺乏深度情感连接；遇危机无应对机制',
    growthAdvice: '每月一次「沉重话题夜」；聊 1 个不愿聊的话题',
    shareCopy: '云同桌型，吃喝玩乐没问题 ☁️',
    radarProfile: { D1: 75, D2: 75, D3: 75, D4: 10, D5: 50, D6: 50 },
    attachmentCombo: 'S/D×S/D',
    conflictPattern: 'withdraw-withdraw',
    stage: 'honeymoon',
    isPublic: true,
  },

  // 20 · 童年回声型
  {
    id: 'CHILDHOOD_ECHO',
    code: 'CHILDHOOD_ECHO',
    name: '童年回声型',
    emoji: '👶',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0245,
    oneLiner: '我们在伴侣身上，重演着和父母的关系',
    description: '一方或双方在原生家庭中形成的创伤模式，在亲密关系中重演。**这是最难也是最有成长潜力的一类**——看懂模式就能跳出循环。',
    hiddenRisks: '模式深植潜意识，自我觉察难',
    growthAdvice: '识别 1 个「我像我妈/我爸的瞬间」；必要时寻求咨询',
    shareCopy: '童年回声型，原来我在重演爸妈 👶',
    radarProfile: { D1: 10, D2: 10, D3: 50, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'F×S',
    conflictPattern: 'pursue-pursue',
    stage: 'stable',
    isPublic: true,
  },

  // 21 · 熔岩重塑型
  {
    id: 'LAVA_REBORN',
    code: 'LAVA_REBORN',
    name: '熔岩重塑型',
    emoji: '🌋',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0123,
    oneLiner: '我们的爱像熔岩，烧得旺也能重塑新生',
    description: '双方都是高激情高焦虑组合，爱得浓烈冲突也激烈。区别于「火星撞地球」的是，你们之间有深层灵魂共鸣——冲突后能相互重塑，关系在一次次熔毁中重生。',
    hiddenRisks: '激情消退时易崩盘；情绪过载',
    growthAdvice: '学会「降温仪式」；建立冲突后拥抱习惯',
    shareCopy: '熔岩重塑型，烧得旺也能重塑新生 🌋',
    radarProfile: { D1: 20, D2: 50, D3: 75, D4: 50, D5: 50, D6: 90 },
    attachmentCombo: 'A×A',
    conflictPattern: 'pursue-pursue',
    stage: 'honeymoon',
    isPublic: true,
  },

  // 22 · 冬日暖阳型
  {
    id: 'WINTER_SUN',
    code: 'WINTER_SUN',
    name: '冬日暖阳型',
    emoji: '☀️',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '他/她的温暖，慢慢治愈了我的焦虑',
    description: '一方安全型，慢慢带动焦虑型伴侣走向安全。这是「治愈型关系」，**最有成长性的组合之一**。',
    hiddenRisks: '安全方易疲惫；需要边界保护',
    growthAdvice: '安全方设定自我充电时间；焦虑方记录「被治愈的瞬间」',
    shareCopy: '冬日暖阳型，慢慢治愈了我的焦虑 ☀️',
    radarProfile: { D1: 65, D2: 75, D3: 75, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'S×A',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: true,
  },

  // 23 · 冰与火型
  {
    id: 'ICE_FIRE',
    code: 'ICE_FIRE',
    name: '冰与火型',
    emoji: '❄️🔥',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我热情似火，你冷若冰霜',
    description: '极端的追-逃组合，激情和冷漠交替。区别于「风筝与线」的是，你们的温差更大，冲突更激烈。',
    hiddenRisks: '长期消耗；易演变为情感虐待',
    growthAdvice: '学习「情绪恒温」技巧；必要时寻求咨询',
    shareCopy: '冰与火型，热情似火冷若冰霜 ❄️🔥',
    radarProfile: { D1: 35, D2: 50, D3: 50, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'A×D',
    conflictPattern: 'pursue-withdraw',
    stage: 'crisis',
    isPublic: true,
  },

  // 24 · 同频共振型
  {
    id: 'RESONANCE',
    code: 'RESONANCE',
    name: '同频共振型',
    emoji: '📡',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0245,
    oneLiner: '我们不需要说话，一个眼神就懂',
    description: '双方高度默契，沟通成本低。这是「烟火余生」的进阶版——不仅有稳定，还有深度连接。',
    hiddenRisks: '容易把默契当理所当然；遇外部冲击时脆弱',
    growthAdvice: '定期「重新认识对方」；接受对方会变化',
    shareCopy: '同频共振型，一个眼神就懂 📡',
    radarProfile: { D1: 75, D2: 75, D3: 75, D4: 75, D5: 75, D6: 75 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: true,
  },

  // 25 · 火山休眠型
  {
    id: 'DORMANT_VOLCANO',
    code: 'DORMANT_VOLCANO',
    name: '火山休眠型',
    emoji: '🌋',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我们表面平静，但火山随时可能喷发',
    description: '双方都压抑情绪，表面和谐实际暗流涌动。区别于「双子星」的是，你们有未解决的深层矛盾。',
    hiddenRisks: '一次爆发可能关系终结',
    growthAdvice: '建立「情绪出口」机制；每月一次「吐槽大会」',
    shareCopy: '火山休眠型，表面平静暗流涌动 🌋',
    radarProfile: { D1: 35, D2: 75, D3: 10, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'D×D',
    conflictPattern: 'withdraw-withdraw',
    stage: 'crisis',
    isPublic: true,
  },

  // 26 · 旅行伴侣型
  {
    id: 'TRAVEL_COMPANION',
    code: 'TRAVEL_COMPANION',
    name: '旅行伴侣型',
    emoji: '🧳',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我们像一起旅行的朋友，互相陪伴但不束缚',
    description: '关系松散但健康，双方都独立。**这是「低浓度高稳定」关系**，适合事业型情侣。',
    hiddenRisks: '激情不足；可能逐渐疏远',
    growthAdvice: '每季度一次「深度旅行」；建立专属仪式',
    shareCopy: '旅行伴侣型，互相陪伴不束缚 🧳',
    radarProfile: { D1: 75, D2: 50, D3: 50, D4: 50, D5: 50, D6: 35 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'honeymoon',
    isPublic: true,
  },

  // 27 · 巢与羽型
  {
    id: 'NEST_FEATHER',
    code: 'NEST_FEATHER',
    name: '巢与羽型',
    emoji: '🪺',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我把你照顾得无微不至，你也离不开我',
    description: '一方过度照顾，一方依赖接受。**这是「共生型关系」**，看似温暖实则不健康。',
    hiddenRisks: '被照顾方失去独立能力；照顾方控制欲增强',
    growthAdvice: '被照顾方独立完成 3 件事；照顾方练习「放手」',
    shareCopy: '巢与羽型，照顾到离不开 🪺',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 35, D6: 50 },
    attachmentCombo: 'A×F',
    conflictPattern: 'pursue-pursue',
    stage: 'stable',
    isPublic: true,
  },

  // 28 · 合伙人型
  {
    id: 'PARTNER',
    code: 'PARTNER',
    name: '合伙人型',
    emoji: '🤝',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0245,
    oneLiner: '我们的关系像一家公司，各司其职',
    description: '关系高度功能化，像合伙人一样分工明确。**优势是稳定，风险是失去情感**。',
    hiddenRisks: '浪漫缺失；可能变成「室友」',
    growthAdvice: '每周一次「不谈正事」时间；保留恋爱感',
    shareCopy: '合伙人型，关系像一家公司 🤝',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 50, D6: 20 },
    attachmentCombo: 'S/D×S/D',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: true,
  },

  // 29 · 候补队员型
  {
    id: 'BENCH_PLAYER',
    code: 'BENCH_PLAYER',
    name: '候补队员型',
    emoji: '🏟️',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0123,
    oneLiner: '我感觉自己是你退而求其次的选择',
    description: '一方感觉自己不是对方的「首选」，关系建立在「将就」之上。**这是最伤自尊的关系模式**。',
    hiddenRisks: '长期自我价值感低；易爆发性分手',
    growthAdvice: '坦诚沟通「我为什么选你」；重建价值感',
    shareCopy: '候补队员型，是时候上场还是退场 🏟️',
    radarProfile: { D1: 20, D2: 50, D3: 50, D4: 50, D5: 20, D6: 50 },
    attachmentCombo: 'A×D',
    conflictPattern: 'pursue-withdraw',
    stage: 'crisis',
    isPublic: true,
  },

  // 30 · 蝉鸣夏日型
  {
    id: 'SUMMER_CICADA',
    code: 'SUMMER_CICADA',
    name: '蝉鸣夏日型',
    emoji: '🎐',
    rarity: 'common',
    genderCombo: 'male-female',
    estimatedRatio: 0.0123,
    oneLiner: '我们的爱情像夏日蝉鸣，热烈但短暂',
    description: '短期高浓度关系，激情主导。**可能是暑期恋、网恋奔现初期、或短期高浓度关系**。',
    hiddenRisks: '激情消退后无基础；易快速结束',
    growthAdvice: '主动讨论「激情退去后我们怎么办」',
    shareCopy: '蝉鸣夏日型，热烈但短暂 🎐',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 20, D5: 20, D6: 90 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'honeymoon',
    isPublic: true,
  },

  // ==================== 5 种稀有类型 ====================

  // R1 · 双生火焰型
  {
    id: 'R_TWIN_FLAME',
    code: 'R_TWIN_FLAME',
    name: '双生火焰型',
    emoji: '✨',
    rarity: 'rare',
    genderCombo: 'male-female',
    estimatedRatio: 0.0061,
    oneLiner: '我们不用说话，一个眼神就完成一场对话',
    description: '这是 Sternberg「完美爱情」的现实版——激情、亲密、承诺三者皆高。**发生率 < 1%**，是所有人向往但很少有人达到的状态。',
    hiddenRisks: '容易把对方当「灵魂伴侣」神化，落差来临时更痛苦',
    growthAdvice: '接受「平凡的一天」；允许对方有缺点',
    shareCopy: '双生火焰型，1% 的稀缺品种 ✨ 测测你们是哪种',
    radarProfile: { D1: 90, D2: 90, D3: 90, D4: 90, D5: 90, D6: 90 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    marketingAngle: '炫耀型稀缺',
    isPublic: true,
  },

  // R2 · 飞蛾扑火型
  {
    id: 'R_MOTH_FLAME',
    code: 'R_MOTH_FLAME',
    name: '飞蛾扑火型',
    emoji: '🔥',
    rarity: 'rare',
    genderCombo: 'male-female',
    estimatedRatio: 0.0123,
    oneLiner: '我知道不该爱你，但停不下来',
    description: '经典「有害但难以割舍」组合。激情极高，但破坏性也大。',
    hiddenRisks: '长期消耗；可能演变为情感虐待',
    growthAdvice: '列「这段关系让我损失的 5 件事」；必要时寻求咨询',
    shareCopy: '飞蛾扑火型，明知不该却放不下 🔥',
    radarProfile: { D1: 10, D2: 50, D3: 75, D4: 50, D5: 50, D6: 90 },
    attachmentCombo: 'A×F',
    conflictPattern: 'pursue-pursue',
    stage: 'crisis',
    marketingAngle: '自嘲型稀缺',
    isPublic: true,
  },

  // R3 · 古井无波型
  {
    id: 'R_STILL_WELL',
    code: 'R_STILL_WELL',
    name: '古井无波型',
    emoji: '💧',
    rarity: 'rare',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我们没什么故事可讲，但每天都想见到对方',
    description: '长期稳定、低冲突、低激情但高亲密。**这是最被低估的关系类型**。',
    hiddenRisks: '容易被外界「不够浪漫」的评价影响',
    growthAdvice: '接受「平淡是福」；不被短视频爱情标准绑架',
    shareCopy: '古井无波型，没什么故事但每天都想见 💧',
    radarProfile: { D1: 65, D2: 65, D3: 65, D4: 65, D5: 65, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    marketingAngle: '反潮流型稀缺',
    isPublic: true,
  },

  // R4 · 凤凰涅槃型
  {
    id: 'R_PHOENIX_REBIRTH',
    code: 'R_PHOENIX_REBIRTH',
    name: '凤凰涅槃型',
    emoji: '🦋',
    rarity: 'rare',
    genderCombo: 'male-female',
    estimatedRatio: 0.0184,
    oneLiner: '我们差点分手，但选择了重新开始',
    description: '经历过严重危机（出轨/冷战/分离）后，**双方都做了真实改变**，关系进入「2.0 版」。',
    hiddenRisks: '旧伤可能被新冲突触发',
    growthAdvice: '庆祝「重生纪念日」；定期检查改变是否还在',
    shareCopy: '凤凰涅槃型，差点分手但选择了重新开始 🦋',
    radarProfile: { D1: 50, D2: 50, D3: 90, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'rebirth',
    marketingAngle: '希望型稀缺',
    isPublic: true,
  },

  // R5 · 两棵树型
  {
    id: 'R_TWO_TREES',
    code: 'R_TWO_TREES',
    name: '两棵树型',
    emoji: '🌳',
    rarity: 'rare',
    genderCombo: 'male-female',
    estimatedRatio: 0.0123,
    oneLiner: '我们各自完整，又互相滋养',
    description: '双方都有强自我、强事业、强社交圈，关系是「加分项」不是「依赖项」。**这是现代人最理想的关系形态**。',
    hiddenRisks: '容易被外界解读为「不够爱」',
    growthAdvice: '明确表达「我选择你，不是需要你」',
    shareCopy: '两棵树型，各自完整又互相滋养 🌳',
    radarProfile: { D1: 75, D2: 50, D3: 50, D4: 65, D5: 75, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    marketingAngle: '现代理想型稀缺',
    isPublic: true,
  },
];
