/**
 * 女女专属情侣类型 seed（15 种，FF-1 ~ FF-15）
 * 仅当双方注册性别都为「女」时触发，不在公共类型百科展示
 * 命名原则：三段式意象化，全部去角色标签化（避免「母女/姐妹」等角色词）
 * estimatedRatio 已归一化到组内总和 100%（2026-07-04 审查修复 W-WC-3）
 */
import type { CoupleTypeInfo } from './types';

export const FEMALE_FEMALE_COUPLE_TYPES: CoupleTypeInfo[] = [
  // FF-1 · 藤蔓速缠型
  {
    id: 'FF_VINE',
    code: 'FF_VINE',
    name: '藤蔓速缠型',
    emoji: '🌱',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 13.1579,
    oneLiner: '我们认识 3 个月就同居了，U-Haul 不是传说',
    description:
      '女女关系经典的「U-Haul」现象——快速同居、快速融合。优势是深度连接，风险是失去自我边界。',
    hiddenRisks: '边界模糊；情绪共振过强；个人空间被压缩',
    growthAdvice: '保留各自空间；不要急于融合生活；建立「独处日」',
    shareCopy: '藤蔓速缠型，U-Haul 不是传说 🌱',
    radarProfile: { D1: 35, D2: 50, D3: 50, D4: 75, D5: 50, D6: 75 },
    attachmentCombo: 'A×A',
    conflictPattern: 'pursue-pursue',
    stage: 'honeymoon',
    isPublic: false,
  },
  // FF-2 · 双焦虑共振型
  {
    id: 'FF_DUAL_ANXIOUS',
    code: 'FF_DUAL_ANXIOUS',
    name: '双焦虑共振型',
    emoji: '🎵',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 10.5263,
    oneLiner: '我们都太在意对方，反而互相消耗',
    description:
      '两个焦虑型女性在一起，情绪共振强烈。女女版的「双螺旋型」——互相需要持续确认，爱得浓烈也消耗。',
    hiddenRisks: '情绪过载；小事易升级；长期消耗',
    growthAdvice: '学习「情绪隔离」技巧；建立独处时间；建立「安全词」机制',
    shareCopy: '双焦虑共振型，太在意反而互相消耗 🎵',
    radarProfile: { D1: 35, D2: 20, D3: 50, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'A×A',
    conflictPattern: 'pursue-pursue',
    stage: 'adjustment',
    isPublic: false,
  },
  // FF-3 · 潮汐交替型
  {
    id: 'FF_TIDAL',
    code: 'FF_TIDAL',
    name: '潮汐交替型',
    emoji: '🌊',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 8.7719,
    oneLiner: '今天我照顾你，明天你照顾我，角色像潮汐一样交替',
    description:
      '女女关系中常见的「照顾角色流动」——不同于固定角色，女女更倾向于轮流承担照顾者与被照顾者。这是女女关系的独特优势。',
    hiddenRisks: '角色不清易生混乱；任一方长期疲惫时失衡',
    growthAdvice: '接受角色流动；定期检查双方负担是否均衡',
    shareCopy: '潮汐交替型，角色像潮汐一样流动 🌊',
    radarProfile: { D1: 65, D2: 50, D3: 50, D4: 75, D5: 75, D6: 50 },
    attachmentCombo: '*×*',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // FF-4 · 双生藤蔓型
  {
    id: 'FF_TWIN_VINE',
    code: 'FF_TWIN_VINE',
    name: '双生藤蔓型',
    emoji: '🌿',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 10.5263,
    oneLiner: '我们不是找到了对方，是和对方一起成为了更好的人',
    description:
      '女女关系中最健康的形态——既有激情，又有深度的情感连接，双方各自完整又互相成就。',
    hiddenRisks: '容易过度理性，忽略感性需求',
    growthAdvice: '保持激情；不要完全变成「闺蜜」；每周一次纯感性对话',
    shareCopy: '双生藤蔓型，彼此的加分项 🌿',
    radarProfile: { D1: 75, D2: 75, D3: 75, D4: 75, D5: 75, D6: 75 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // FF-5 · 猫系恋人型
  {
    id: 'FF_CAT',
    code: 'FF_CAT',
    name: '猫系恋人型',
    emoji: '🐈',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 7.0175,
    oneLiner: '我们都需要空间，但偶尔黏一下',
    description:
      '双方都回避型依恋，关系松散但健康。女女版的「双子星」——各自独立，偶尔靠近。',
    hiddenRisks: '关系温度持续低；任一方遇新刺激易动摇',
    growthAdvice: '主动制造亲密时刻；避免关系冷却；每周一次「深度对话」',
    shareCopy: '猫系恋人型，各自独立偶尔黏 🐈',
    radarProfile: { D1: 50, D2: 75, D3: 50, D4: 20, D5: 50, D6: 50 },
    attachmentCombo: 'D×D',
    conflictPattern: 'withdraw-withdraw',
    stage: 'stable',
    isPublic: false,
  },
  // FF-6 · 破茧成蝶型
  {
    id: 'FF_COCOON',
    code: 'FF_COCOON',
    name: '破茧成蝶型',
    emoji: '🦋',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 7.0175,
    oneLiner: '和她在一起，我才真正认识自己',
    description:
      '女女关系中常见的「自我认同探索」——一方或双方在关系中完成出柜/自我接纳。关系本身成为成长的催化剂。',
    hiddenRisks: '自我认同压力转嫁伴侣；关系承载过重',
    growthAdvice: '接受自我认同是持续过程；不要把全部压力给伴侣；保留独立支持系统',
    shareCopy: '破茧成蝶型，和她在一起才认识自己 🦋',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 50, D6: 50 },
    attachmentCombo: '*×*',
    conflictPattern: 'repair',
    stage: 'honeymoon',
    isPublic: false,
  },
  // FF-7 · 冰下暗流型
  {
    id: 'FF_UNDERCURRENT',
    code: 'FF_UNDERCURRENT',
    name: '冰下暗流型',
    emoji: '❄️',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 7.0175,
    oneLiner: '我们从不吵架，但每件事都在较劲',
    description:
      '女女关系中的「隐性攻击」——表面和谐实际暗流涌动。比 overt conflict 更伤关系，因为问题从未被真正处理。',
    hiddenRisks: '长期压抑易爆发性崩溃；信任持续流失',
    growthAdvice: '学习直接表达；不要用「沉默」当武器；建立「情绪出口」机制',
    shareCopy: '冰下暗流型，表面和谐暗流涌动 ❄️',
    radarProfile: { D1: 35, D2: 75, D3: 10, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: '*×*',
    conflictPattern: 'withdraw-withdraw',
    stage: 'crisis',
    isPublic: false,
  },
  // FF-8 · 并肩闪耀型
  {
    id: 'FF_SHINE_TOGETHER',
    code: 'FF_SHINE_TOGETHER',
    name: '并肩闪耀型',
    emoji: '✨',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 7.0175,
    oneLiner: '我们各自精彩，又互相成就',
    description:
      '女女版的「两棵树型」——双方都有强自我、强事业、强社交圈，关系是「加分项」不是「依赖项」。',
    hiddenRisks: '容易被外界解读为「不够爱」；浪漫仪式感缺失',
    growthAdvice: '庆祝对方成就；不要比较；明确表达「我选择你，不是需要你」',
    shareCopy: '并肩闪耀型，各自精彩又互相成就 ✨',
    radarProfile: { D1: 75, D2: 50, D3: 50, D4: 65, D5: 75, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // FF-9 · 双塔守望型
  {
    id: 'FF_TWIN_TOWER',
    code: 'FF_TWIN_TOWER',
    name: '双塔守望型',
    emoji: '🏰',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 5.2632,
    oneLiner: '我们没什么故事可讲，但每天都想见到她',
    description:
      '长期稳定、低冲突、低激情但高亲密的女女关系。这是最被低估的关系类型——平淡是福。',
    hiddenRisks: '容易被外界「不够浪漫」的评价影响',
    growthAdvice: '接受「平淡是福」；不被短视频爱情标准绑架',
    shareCopy: '双塔守望型，没什么故事但每天都想见 🏰',
    radarProfile: { D1: 65, D2: 65, D3: 65, D4: 65, D5: 65, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // FF-10 · 灯塔与舟型
  {
    id: 'FF_LIGHTHOUSE',
    code: 'FF_LIGHTHOUSE',
    name: '灯塔与舟型',
    emoji: '🔦',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 4.3860,
    oneLiner: '她像光一样照着我往前走，我也是自愿跟随的舟',
    description:
      '年龄差或阅历差较大的女女关系，常见「引导者-跟随者」动态。优势是成长快，风险是被引导方失去自我。',
    hiddenRisks: '被引导方依赖过重；引导方易疲惫',
    growthAdvice: '被引导方独立做 3 个决定；引导方练习「不指点」',
    shareCopy: '灯塔与舟型，她照着我往前走 🔦',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 50, D6: 50 },
    attachmentCombo: 'S×A|S×F',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // FF-11 · 风筝与线型
  {
    id: 'FF_KITE_LINE',
    code: 'FF_KITE_LINE',
    name: '风筝与线型',
    emoji: '🪁',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 5.2632,
    oneLiner: '我越追她越跑，她越跑我越慌',
    description:
      '女女版的「追-逃循环」——一方焦虑追逐确认，一方回避退缩自保。修复关键：看懂循环，关系质量能快速提升。',
    hiddenRisks: '长期循环会让追逐方耗尽、回避方窒息',
    growthAdvice: '追逐方练习「自我安抚」；回避方练习「先回应再退避」',
    shareCopy: '风筝与线型，我追她跑 🪁 测测你们的真相',
    radarProfile: { D1: 50, D2: 20, D3: 20, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'A×D',
    conflictPattern: 'pursue-withdraw',
    stage: 'adjustment',
    isPublic: false,
  },
  // FF-12 · 烟火冷却型
  {
    id: 'FF_FIREWORK_COOLING',
    code: 'FF_FIREWORK_COOLING',
    name: '烟火冷却型',
    emoji: '🎆',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 4.3860,
    oneLiner: '刚在一起时烟火绚烂，现在正在学怎么收拾余烬',
    description:
      '女女关系中常见的「蜜月期结束」过渡态——激情退去后真实关系才开始。关键不是分手，是建立冲突应对机制。',
    hiddenRisks: '激情消退易误判为「不爱」；缺乏冲突肌肉',
    growthAdvice: '主动讨论「如果我们吵架了怎么办」；建立「修复尝试」暗号',
    shareCopy: '烟火冷却型，正在学怎么收拾余烬 🎆',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 75, D6: 50 },
    attachmentCombo: '*×*',
    conflictPattern: 'repair',
    stage: 'honeymoon',
    isPublic: false,
  },
  // FF-13 · 老井深泉型
  {
    id: 'FF_OLD_WELL',
    code: 'FF_OLD_WELL',
    name: '老井深泉型',
    emoji: '🪣',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 3.5088,
    oneLiner: '我们都不太会吵架，也就没什么大事',
    description:
      '一方回避一方安全，关系温度低但稳定。功能性强但情感浓度低，常见于长期相处的女女关系。',
    hiddenRisks: '关系温度持续低；任一方遇情感诱惑易动摇',
    growthAdvice: '每周一次「情绪分享」；建立「深度对话」习惯',
    shareCopy: '老井深泉型，不喧哗但不会干涸 🪣',
    radarProfile: { D1: 60, D2: 60, D3: 60, D4: 60, D5: 60, D6: 60 },
    attachmentCombo: 'D×S',
    conflictPattern: 'withdraw-pursue',
    stage: 'stable',
    isPublic: false,
  },
  // FF-14 · 凤凰涅槃型
  {
    id: 'FF_PHOENIX',
    code: 'FF_PHOENIX',
    name: '凤凰涅槃型',
    emoji: '🔥',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 2.6316,
    oneLiner: '我们差点散了，但选择了重新开始',
    description:
      '经历过严重危机（出轨/冷战/分离/出柜冲突）后，双方都做了真实改变，关系进入「2.0 版」。',
    hiddenRisks: '旧伤可能被新冲突触发；信任需要持续重建',
    growthAdvice: '庆祝「重生纪念日」；定期检查改变是否还在',
    shareCopy: '凤凰涅槃型，差点散了又重新开始 🔥',
    radarProfile: { D1: 50, D2: 50, D3: 90, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: '*×*',
    conflictPattern: 'repair',
    stage: 'rebirth',
    isPublic: false,
  },
  // FF-15 · 候鸟迁徙型
  {
    id: 'FF_MIGRATORY_BIRD',
    code: 'FF_MIGRATORY_BIRD',
    name: '候鸟迁徙型',
    emoji: '🕊️',
    rarity: 'common',
    genderCombo: 'female-female',
    estimatedRatio: 3.5088,
    oneLiner: '我们的爱情，一半在视频里，一半在机票里',
    description:
      '女女异地恋是「阶段型特殊状态」，本身不是问题，问题是缺乏「结束异地的时间表」。LGBTQ+ 异地更难寻支持网络。',
    hiddenRisks: '缺乏身体接触；信任消耗快；支持网络薄弱',
    growthAdvice: '设定异地结束日期；每月一次见面；每日 5 分钟视频',
    shareCopy: '候鸟迁徙型，机票攒了一摞 🕊️',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 50, D5: 75, D6: 20 },
    attachmentCombo: '*×*',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
];
