/**
 * 男男专属情侣类型（15 种，隐藏触发）
 * 仅当双方注册性别都为「男」时触发，不在公共类型百科展示
 * 数据来源：docs/COUPLE_TYPES.md v2.1（MM-1 ~ MM-15）
 * 雷达图数值映射：极高90 / 高75 / 中高65 / 中50 / 中低35 / 低20 / 极低10 / 未提及50
 * estimatedRatio 已归一化到组内总和 100%（2026-07-04 审查修复 W-WC-3）
 */
import type { CoupleTypeInfo } from './types';

export const MALE_MALE_COUPLE_TYPES: CoupleTypeInfo[] = [
  // MM-1
  {
    id: 'MM_MIRROR',
    code: 'MM_MIRROR',
    name: '镜像对决型',
    emoji: '🪞',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 10.0000,
    oneLiner: '我们太像了，像照镜子一样互相较劲',
    description:
      '两个相似度高的人在一起，既互相理解又互相竞争。这是男男关系中最常见的模式——优势是深度共鸣，风险是失去新鲜感。',
    hiddenRisks: '长期同质化易生厌倦；小事易升级为胜负之争',
    growthAdvice: '接受差异；不要每件事都比；保留各自独立爱好',
    shareCopy: '镜像对决型，像照镜子一样较劲 🪞 测测你们',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'A×A|S×S',
    conflictPattern: 'pursue-pursue',
    stage: 'adjustment',
    isPublic: false,
  },
  // MM-2
  {
    id: 'MM_LIGHTHOUSE',
    code: 'MM_LIGHTHOUSE',
    name: '灯塔与舟型',
    emoji: '🔦',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 8.3333,
    oneLiner: '他像光一样照着我往前走，我也是自愿跟随的舟',
    description:
      '年龄差或阅历差较大的男男关系，常见「引导者-跟随者」动态。优势是成长快，风险是权力不对等，被引导方可能逐渐失去自我。',
    hiddenRisks: '被引导方依赖过重；引导方易疲惫',
    growthAdvice: '被引导方独立做 3 个决定；引导方练习「不指点」',
    shareCopy: '灯塔与舟型，他照着我往前走 🔦',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 50, D6: 50 },
    attachmentCombo: 'S×A|S×F',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // MM-3
  {
    id: 'MM_PARALLEL',
    code: 'MM_PARALLEL',
    name: '并肩同行型',
    emoji: '👣',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 12.5000,
    oneLiner: '没有谁主外谁主内，我们一起走',
    description:
      '平等型男男关系，没有明显的角色分工束缚。这是男男关系最健康的形态之一——双方各自完整又互相成就。',
    hiddenRisks: '容易把平等当理所当然；遇外部冲击时缺乏「角色缓冲」',
    growthAdvice: '保持平等；定期讨论分工是否仍然舒适',
    shareCopy: '并肩同行型，没有谁主外谁主内 👣',
    radarProfile: { D1: 65, D2: 65, D3: 65, D4: 65, D5: 65, D6: 65 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // MM-4
  {
    id: 'MM_DUAL_NEST',
    code: 'MM_DUAL_NEST',
    name: '双巢共孵型',
    emoji: '🪺',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 6.6667,
    oneLiner: '我们俩都想照顾对方，结果谁也照顾不好自己',
    description:
      '双方都扮演「照顾者」角色，关系温暖但可能过度依赖。男男关系中的「双焦虑」组合——互相需要持续确认。',
    hiddenRisks: '情绪过载；边界模糊；长期消耗',
    growthAdvice: '各自保留独处时间；避免过度干预对方；建立「自我充电」机制',
    shareCopy: '双巢共孵型，互相照顾到失去自己 🪺',
    radarProfile: { D1: 35, D2: 50, D3: 50, D4: 75, D5: 75, D6: 50 },
    attachmentCombo: 'A×A',
    conflictPattern: 'pursue-pursue',
    stage: 'adjustment',
    isPublic: false,
  },
  // MM-5
  {
    id: 'MM_HUNTER_FOX',
    code: 'MM_HUNTER_FOX',
    name: '猎人与狐型',
    emoji: '🦊',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 6.6667,
    oneLiner: '他追我躲，我躲他追，永远在博弈',
    description:
      '男男版的「追-逃循环」，但双方都是男性，权力博弈更激烈。修复关键：追逐方学会自我安抚，回避方学会先回应再退避。',
    hiddenRisks: '长期循环会让追逐方耗尽、回避方窒息',
    growthAdvice: '学习「暂停-回归」机制；避免权力斗争升级',
    shareCopy: '猎人与狐型，永远在博弈 🦊 测测你们',
    radarProfile: { D1: 50, D2: 20, D3: 20, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: 'A×D',
    conflictPattern: 'pursue-withdraw',
    stage: 'adjustment',
    isPublic: false,
  },
  // MM-6
  {
    id: 'MM_SHIELD_WARRIOR',
    code: 'MM_SHIELD_WARRIOR',
    name: '并肩战士型',
    emoji: '🛡️',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 10.0000,
    oneLiner: '我们要对抗的不只是关系问题，还有世界',
    description:
      '男男关系面临独特的社会压力，「并肩作战」是常见的健康应对模式——外部压力反而让关系更紧密。',
    hiddenRisks: '容易把外部压力转嫁为内部矛盾；浪漫被「战友感」覆盖',
    growthAdvice: '区分「外部压力」和「内部矛盾」；保留纯恋爱时刻',
    shareCopy: '并肩战士型，对抗世界也对抗彼此 🛡️',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 75, D6: 50 },
    attachmentCombo: 'S/D×S/D',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // MM-7
  {
    id: 'MM_LOCKED_ROOM',
    code: 'MM_LOCKED_ROOM',
    name: '上锁的房间型',
    emoji: '🔒',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 6.6667,
    oneLiner: '我们的关系只有我们自己知道',
    description:
      '未出柜的男男关系，secrecy 本身就会成为关系压力——需要共同管理「谁能知道」，长期消耗情感带宽。',
    hiddenRisks: '长期 secrecy 导致关系「不可见」；社交圈割裂',
    growthAdvice: '讨论出柜时间表；建立「安全空间」；区分「隐私」和「隐藏」',
    shareCopy: '（仅内部可见，不建议公开分享）',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 20, D5: 50, D6: 50 },
    attachmentCombo: '*×*',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // MM-8
  {
    id: 'MM_GARDEN_WINDOW',
    code: 'MM_GARDEN_WINDOW',
    name: '花园与窗型',
    emoji: '🌷',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 8.3333,
    oneLiner: '我们有协议，爱是爱，性是性，花园里有窗',
    description:
      '开放式关系在男男关系中比例较高。关键不是开放本身，是协议是否清晰、双方是否真的同意。健康的开放关系反而需要更强的沟通能力。',
    hiddenRisks: '协议模糊时易生嫉妒；一方「假同意」会埋雷',
    growthAdvice: '定期复盘协议；区分「安全感」和「排他性」；建立「嫉妒应对」机制',
    shareCopy: '花园与窗型，爱是爱性是性 🌷',
    radarProfile: { D1: 75, D2: 75, D3: 50, D4: 50, D5: 75, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // MM-9
  {
    id: 'MM_DUAL_TOWER',
    code: 'MM_DUAL_TOWER',
    name: '双塔守望型',
    emoji: '🏰',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 6.6667,
    oneLiner: '我们各自独立，又互相守望',
    description:
      '男男版的「双生藤蔓型」—— 双方都有强自我、强事业，关系是「加分项」不是「依赖项」。这是现代人最理想的关系形态之一。',
    hiddenRisks: '容易被外界解读为「不够爱」；情感浓度可能偏低',
    growthAdvice: '明确表达「我选择你，不是需要你」；定期制造深度连接',
    shareCopy: '双塔守望型，各自独立又互相守望 🏰',
    radarProfile: { D1: 75, D2: 50, D3: 50, D4: 65, D5: 75, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // MM-10
  {
    id: 'MM_FIREWORKS_COOLING',
    code: 'MM_FIREWORKS_COOLING',
    name: '烟火冷却型',
    emoji: '🎆',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 5.8333,
    oneLiner: '刚在一起时烟火绚烂，现在正在学怎么收拾余烬',
    description:
      '男男关系中常见的「蜜月期结束」过渡态——激情退去后真实关系才开始。关键不是分手，是建立冲突应对机制。',
    hiddenRisks: '激情消退易误判为「不爱」；缺乏冲突肌肉',
    growthAdvice: '主动讨论「如果我们吵架了怎么办」；建立「修复尝试」暗号',
    shareCopy: '烟火冷却型，正在学怎么收拾余烬 🎆',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 75, D5: 75, D6: 50 },
    attachmentCombo: '*×*',
    conflictPattern: 'repair',
    stage: 'adjustment',
    isPublic: false,
  },
  // MM-11
  {
    id: 'MM_TIDE_MOON',
    code: 'MM_TIDE_MOON',
    name: '潮汐与月型',
    emoji: '🌙',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 4.1667,
    oneLiner: '我们各自有节奏，偶尔靠近偶尔远',
    description:
      '男男版的「双子星型」—— 双方都回避型依恋，互相给空间但也互相不深入。表面和谐实际是「情感休眠」，稳定但危险。',
    hiddenRisks: '关系温度持续走低；任一方遇外部刺激易崩塌',
    growthAdvice: '每周一次「深度对话夜」；从分享小情绪开始重建亲密',
    shareCopy: '潮汐与月型，偶尔靠近偶尔远 🌙',
    radarProfile: { D1: 50, D2: 75, D3: 50, D4: 20, D5: 50, D6: 50 },
    attachmentCombo: 'D×D',
    conflictPattern: 'withdraw-withdraw',
    stage: 'stable',
    isPublic: false,
  },
  // MM-12
  {
    id: 'MM_OLD_TREE_NEW_BUD',
    code: 'MM_OLD_TREE_NEW_BUD',
    name: '老树新芽型',
    emoji: '🌳',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 3.3333,
    oneLiner: '我们差点散了，但选择了重新发芽',
    description:
      '经历过严重危机（出轨/冷战/分离/出柜冲突）后，双方都做了真实改变，关系进入「2.0 版」。男男关系中因外部压力导致危机的比例较高。',
    hiddenRisks: '旧伤可能被新冲突触发；信任需要持续重建',
    growthAdvice: '庆祝「重生纪念日」；定期检查改变是否还在',
    shareCopy: '老树新芽型，差点散了又重新发芽 🌳',
    radarProfile: { D1: 50, D2: 50, D3: 90, D4: 50, D5: 50, D6: 50 },
    attachmentCombo: '*×*',
    conflictPattern: 'repair',
    stage: 'rebirth',
    isPublic: false,
  },
  // MM-13
  {
    id: 'MM_OLD_WELL',
    code: 'MM_OLD_WELL',
    name: '古井静守型',
    emoji: '🪘',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 4.1667,
    oneLiner: '我们没什么故事可讲，但每天都想见到他',
    description:
      '长期稳定、低冲突、低激情但高亲密的男男关系。这是最被低估的关系类型——平淡是福。',
    hiddenRisks: '容易被外界「不够浪漫」的评价影响',
    growthAdvice: '接受「平淡是福」；不被短视频爱情标准绑架',
    shareCopy: '古井静守型，没什么故事但每天都想见 🪘',
    radarProfile: { D1: 65, D2: 65, D3: 65, D4: 65, D5: 65, D6: 50 },
    attachmentCombo: 'S×S',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // MM-14
  {
    id: 'MM_MIGRATORY_BIRD',
    code: 'MM_MIGRATORY_BIRD',
    name: '候鸟迁徙型',
    emoji: '🕊️',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 4.1667,
    oneLiner: '我们的爱情，一半在视频里，一半在机票里',
    description:
      '男男异地恋是「阶段型特殊状态」，本身不是问题，问题是缺乏「结束异地的时间表」。异地恋成功率与「是否有明确结束时间」强相关。',
    hiddenRisks: '缺乏身体接触；信任消耗快；LGBTQ+ 异地更难寻支持',
    growthAdvice: '设定异地结束日期；每月一次见面；每日 5 分钟视频',
    shareCopy: '候鸟迁徙型，机票攒了一摞 🕊️',
    radarProfile: { D1: 50, D2: 50, D3: 50, D4: 50, D5: 75, D6: 20 },
    attachmentCombo: '*×*',
    conflictPattern: 'repair',
    stage: 'stable',
    isPublic: false,
  },
  // MM-15
  {
    id: 'MM_MARS_EARTH',
    code: 'MM_MARS_EARTH',
    name: '火星撞地球型',
    emoji: '☄️',
    rarity: 'common',
    genderCombo: 'male-male',
    estimatedRatio: 2.5000,
    oneLiner: '我们吵得邻居都搬走了，但还爱着',
    description:
      '男男版的高冲突高激情组合——双方都情绪化，冲突激烈但修复也快。爱得浓烈吵得也凶，缺乏承诺和亲密的稳固基础。',
    hiddenRisks: '长期情绪过载，3-5 年后易崩盘；易演变为情感虐待',
    growthAdvice: '建立「吵架红线」（不摔门/不拉黑/不过夜）；每月复盘一次',
    shareCopy: '火星撞地球型，邻居都搬走了 ☄️',
    radarProfile: { D1: 20, D2: 10, D3: 75, D4: 50, D5: 50, D6: 75 },
    attachmentCombo: 'A×F',
    conflictPattern: 'pursue-pursue',
    stage: 'crisis',
    isPublic: false,
  },
];
