import type { TestBank } from './types';

export const MALE_TEST_BANK: TestBank = {
  gender: 'male',
  version: 'v2-2026-07',
  questions: [
    // ==================== D1 · 依恋安全性 ====================
    {
      id: 'M-Q1',
      dimension: 'D1',
      kind: 'scale',
      stem: '她 6 小时没回你消息，但发了朋友圈。你的第一反应更接近？',
      options: [
        { label: 'A', text: '可能在忙，等下就回', scoring: { D1: 25 }, attachment: 'S' },
        { label: 'B', text: '是不是我哪句话说错了', scoring: { D1: 10 }, attachment: 'A' },
        { label: 'C', text: '算了，我也去做自己的事', scoring: { D1: 5 }, attachment: 'D' },
        { label: 'D', text: '我先做自己的事，但晚点要问清楚', scoring: { D1: 25 }, attachment: 'S' },
      ],
      rationale: '测焦虑激活（ECR-R）',
    },
    {
      id: 'M-Q2',
      dimension: 'D1',
      kind: 'scale',
      stem: '她突然情绪崩溃大哭，你内心的真实反应是？',
      options: [
        { label: 'A', text: '想立刻抱住她，问怎么了', scoring: { D1: 25 }, attachment: 'S' },
        { label: 'B', text: '觉得慌张，不知道该说什么但不会走开', scoring: { D1: 10 }, attachment: 'A' },
        { label: 'C', text: '觉得有点想逃离，希望她自己冷静下来', scoring: { D1: 5 }, attachment: 'D' },
        { label: 'D', text: '想解决问题，但不知道从哪入手', scoring: { D1: 0 }, attachment: 'F' },
      ],
      rationale: '测回避倾向',
    },
    {
      id: 'M-Q3',
      dimension: 'D1',
      kind: 'scale',
      stem: '你觉得她爱你，主要是因为？',
      options: [
        { label: 'A', text: '你值得被爱，你们互相成就', scoring: { D1: 25 }, attachment: 'S' },
        { label: 'B', text: '你足够努力地讨好她', scoring: { D1: 10 }, attachment: 'A' },
        { label: 'C', text: '你条件不错，她找不到更好的', scoring: { D1: 5 }, attachment: 'D' },
        { label: 'D', text: '你也不确定，可能就是一时激情', scoring: { D1: 0 }, attachment: 'F' },
      ],
      rationale: '测依恋工作模型',
    },
    {
      id: 'M-Q4',
      dimension: 'D1',
      kind: 'scale',
      stem: '你压力大时，更希望她怎么做？',
      options: [
        { label: 'A', text: '陪你聊聊，但给你空间', scoring: { D1: 25 }, attachment: 'S' },
        { label: 'B', text: '一直问你「怎么了」，让你觉得被关注', scoring: { D1: 10 }, attachment: 'A' },
        { label: 'C', text: '别打扰你，让你自己消化', scoring: { D1: 5 }, attachment: 'D' },
        { label: 'D', text: '帮你解决问题，而不是只听你说', scoring: { D1: 0 }, attachment: 'F' },
      ],
      rationale: '测情绪调节策略',
    },
    {
      id: 'M-Q5',
      dimension: 'funny',
      kind: 'funny',
      isFunny: true,
      stem: '如果她一定要养一只你讨厌的宠物，你会？',
      options: [
        { label: 'A', text: '妥协，反正她也开心', scoring: { D1: 20 } },
        { label: 'B', text: '答应但暗暗不爽，时不时念叨', scoring: { D1: 12 } },
        { label: 'C', text: '坚决反对，养了也不理它', scoring: { D1: 5 } },
        { label: 'D', text: '表面同意，偷偷送走', scoring: { D1: 0 } },
      ],
      rationale: '无厘头 · 测控制欲（控制欲高者依恋安全性低）',
    },
    // ==================== D2 · 沟通质量 ====================
    {
      id: 'M-Q6',
      dimension: 'D2',
      kind: 'scale',
      stem: '她又把家里弄得乱七八糟，你的第一句话更像？',
      options: [
        { label: 'A', text: '亲爱的，能不能一起收拾下', scoring: { D2: 25 } },
        { label: 'B', text: '你怎么永远这么邋遢', scoring: { D2: 5 } },
        { label: 'C', text: '我累了，不想再说', scoring: { D2: 5 } },
        { label: 'D', text: '行，那我收拾，你继续躺着', scoring: { D2: 5 } },
      ],
      rationale: '测批评（Gottman 四骑士）',
    },
    {
      id: 'M-Q7',
      dimension: 'D2',
      kind: 'scale',
      stem: '她讲了一个你觉得很幼稚的观点，你的反应更接近？',
      options: [
        { label: 'A', text: '认真听完，再说出自己的看法', scoring: { D2: 25 } },
        { label: 'B', text: '翻白眼或冷笑', scoring: { D2: 0 } },
        { label: 'C', text: '直接打断「你别说了」', scoring: { D2: 5 } },
        { label: 'D', text: '敷衍点头「你说得对」', scoring: { D2: 5 } },
      ],
      rationale: '测蔑视',
    },
    {
      id: 'M-Q8',
      dimension: 'D2',
      kind: 'scale',
      stem: '她说「你最近都不怎么关心我」，你的第一反应是？',
      options: [
        { label: 'A', text: '对不起，我最近确实忙，具体是哪件事让你这么觉得', scoring: { D2: 25 } },
        { label: 'B', text: '我哪有不关心，我昨天才...', scoring: { D2: 5 } },
        { label: 'C', text: '你自己呢？你也没关心我', scoring: { D2: 0 } },
        { label: 'D', text: '沉默不说话', scoring: { D2: 5 } },
      ],
      rationale: '测防御',
    },
    {
      id: 'M-Q9',
      dimension: 'D2',
      kind: 'scale',
      stem: '吵架吵到一半，你的反应更像？',
      options: [
        { label: 'A', text: '越说越激动，必须当场说清楚', scoring: { D2: 10 } },
        { label: 'B', text: '突然不想说了，转身走人或看手机', scoring: { D2: 0 } },
        { label: 'C', text: '提议「我们都冷静 10 分钟再聊」', scoring: { D2: 25 } },
        { label: 'D', text: '妥协道歉，只想快点结束', scoring: { D2: 5 } },
      ],
      rationale: '测筑墙',
    },
    {
      id: 'M-Q10',
      dimension: 'funny',
      kind: 'funny',
      isFunny: true,
      stem: '如果你们俩是游戏里的角色，你觉得你们的配合像？',
      options: [
        { label: 'A', text: '坦克 + 奶妈：互补型，各司其职', scoring: { D2: 20 } },
        { label: 'B', text: '双输出：火力很猛但没人保命', scoring: { D2: 15 } },
        { label: 'C', text: '双辅助：谁也打不死怪', scoring: { D2: 10 } },
        { label: 'D', text: '一个挂机一个 solo：各玩各的', scoring: { D2: 5 } },
      ],
      rationale: '无厘头 · 测沟通风格（游戏梗）',
    },
    // ==================== D3 · 冲突修复 ====================
    {
      id: 'M-Q11',
      dimension: 'D3',
      kind: 'scale',
      stem: '吵架后第二天早上，谁更可能先开口说话？',
      options: [
        { label: 'A', text: '我，我受不了冷战', scoring: { D3: 20 } },
        { label: 'B', text: '她，她总是先服软', scoring: { D3: 5 } },
        { label: 'C', text: '我们一般都各忙各的，自然就和好了', scoring: { D3: 25 } },
        { label: 'D', text: '谁都不开口，能冷战 3 天以上', scoring: { D3: 0 } },
      ],
      rationale: '测修复发起',
    },
    {
      id: 'M-Q12',
      dimension: 'D3',
      kind: 'scale',
      stem: '她吵架后递给你一杯水/发了个表情包，你会？',
      options: [
        { label: 'A', text: '接住，知道这是台阶', scoring: { D3: 25 } },
        { label: 'B', text: '不理，觉得这点小动作算什么', scoring: { D3: 0 } },
        { label: 'C', text: '更生气，觉得她在敷衍', scoring: { D3: 5 } },
        { label: 'D', text: '接住但心里记着，下次吵架翻旧账', scoring: { D3: 5 } },
      ],
      rationale: '测修复接收',
    },
    {
      id: 'M-Q13',
      dimension: 'D3',
      kind: 'scale',
      stem: '吵完架和好后，你的情绪会？',
      options: [
        { label: 'A', text: '真的过去了，不影响接下来几天', scoring: { D3: 25 } },
        { label: 'B', text: '表面和好，但心里还有疙瘩', scoring: { D3: 10 } },
        { label: 'C', text: '反复回想吵架细节，越想越气', scoring: { D3: 5 } },
        { label: 'D', text: '反而更爱她了，有种「危机过后」的亲密', scoring: { D3: 25 } },
      ],
      rationale: '测情绪后效',
    },
    {
      id: 'M-Q14',
      dimension: 'D3',
      kind: 'scale',
      stem: '你们吵架最常见的模式是？',
      options: [
        { label: 'A', text: '我追着说，她越躲越远', scoring: { D3: 10 } },
        { label: 'B', text: '两人都越说越激动，最后抱头痛哭', scoring: { D3: 15 } },
        { label: 'C', text: '都闷着不说，最后莫名其妙和好', scoring: { D3: 10 } },
        { label: 'D', text: '我先炸，她后炸，然后轮流认错', scoring: { D3: 15 } },
      ],
      rationale: '测冲突模式',
    },
    {
      id: 'M-Q15',
      dimension: 'funny',
      kind: 'funny',
      isFunny: true,
      stem: '你们为「今晚吃什么」吵起来了，最后怎么解决？',
      options: [
        { label: 'A', text: '我让她选，反正她开心就好', scoring: { D3: 20 } },
        { label: 'B', text: '石头剪刀布，愿赌服输', scoring: { D3: 15 } },
        { label: 'C', text: '各吃各的，冷战一顿', scoring: { D3: 5 } },
        { label: 'D', text: '我选了，但她全程黑脸', scoring: { D3: 10 } },
      ],
      rationale: '无厘头 · 测妥协方式',
    },
    // ==================== D4 · 共同意义 ====================
    {
      id: 'M-Q16',
      dimension: 'D4',
      kind: 'scale',
      stem: '聊到 5 年后的生活，你们俩的画面是？',
      options: [
        { label: 'A', text: '高度一致，我们经常聊这个', scoring: { D4: 25 } },
        { label: 'B', text: '大方向一样，细节没细聊', scoring: { D4: 15 } },
        { label: 'C', text: '各想各的，谁也没问过对方', scoring: { D4: 5 } },
        { label: 'D', text: '我们刻意回避这个话题，怕聊崩', scoring: { D4: 0 } },
      ],
      rationale: '测共同愿景',
    },
    {
      id: 'M-Q17',
      dimension: 'D4',
      kind: 'scale',
      stem: '如果中了 1000 万，你们最可能因为什么吵架？',
      options: [
        { label: 'A', text: '怎么花：消费观差异', scoring: { D4: 5 } },
        { label: 'B', text: '给谁：双方家庭分配', scoring: { D4: 10 } },
        { label: 'C', text: '不吵，我们对钱的想法一致', scoring: { D4: 25 } },
        { label: 'D', text: '我们不会因为钱吵架，会为别的吵', scoring: { D4: 5 } },
      ],
      rationale: '测价值观对齐',
    },
    {
      id: 'M-Q18',
      dimension: 'D4',
      kind: 'scale',
      stem: '你们俩共同的「专属仪式」有几种？（纪念日不算）',
      options: [
        { label: 'A', text: '3 种以上，我们创造了很多专属习惯', scoring: { D4: 25 } },
        { label: 'B', text: '1-2 种，主要节日会一起过', scoring: { D4: 15 } },
        { label: 'C', text: '没有特别的，想到什么做什么', scoring: { D4: 5 } },
        { label: 'D', text: '想要有，但总是没坚持下来', scoring: { D4: 10 } },
      ],
      rationale: '测仪式感',
    },
    {
      id: 'M-Q19',
      dimension: 'D4',
      kind: 'scale',
      stem: '她的朋友圈/社交圈，你的融入程度？',
      options: [
        { label: 'A', text: '大部分朋友都认识，经常一起聚', scoring: { D4: 25 } },
        { label: 'B', text: '认识几个，偶尔见面', scoring: { D4: 15 } },
        { label: 'C', text: '几乎不认识，各玩各的', scoring: { D4: 5 } },
        { label: 'D', text: '想融入但她不太愿意带我去', scoring: { D4: 5 } },
      ],
      rationale: '测身份认同',
    },
    // ==================== D5 · 信任承诺 ====================
    {
      id: 'M-Q20',
      dimension: 'D5',
      kind: 'scale',
      stem: '她手机收到一条异性发来的暧昧消息，你的第一反应？',
      options: [
        { label: 'A', text: '相信她会处理，不慌', scoring: { D5: 25 } },
        { label: 'B', text: '想问清楚，但不会大吵', scoring: { D5: 15 } },
        { label: 'C', text: '立刻翻手机/质问', scoring: { D5: 5 } },
        { label: 'D', text: '假装没看到，但心里记一辈子', scoring: { D5: 5 } },
      ],
      rationale: '测信任基线',
    },
    {
      id: 'M-Q21',
      dimension: 'D5',
      kind: 'scale',
      stem: '如果她患重病需要长期照顾（5 年+），你的真实想法？',
      options: [
        { label: 'A', text: '当然是我照顾，毫不犹豫', scoring: { D5: 25 } },
        { label: 'B', text: '会照顾，但担心自己撑不住', scoring: { D5: 15 } },
        { label: 'C', text: '会出钱请护工，但我做不到全职照顾', scoring: { D5: 5 } },
        { label: 'D', text: '不确定，没想过这种事', scoring: { D5: 0 } },
      ],
      rationale: '测承诺深度',
    },
    {
      id: 'M-Q22',
      dimension: 'D5',
      kind: 'scale',
      stem: '她拿到一个 dream offer，但在另一个城市，你会？',
      options: [
        { label: 'A', text: '一起搬，重新开始', scoring: { D5: 25 } },
        { label: 'B', text: '异地恋撑一段时间看情况', scoring: { D5: 15 } },
        { label: 'C', text: '让她放弃 offer', scoring: { D5: 5 } },
        { label: 'D', text: '不知道，要看具体情况', scoring: { D5: 5 } },
      ],
      rationale: '测牺牲意愿',
    },
    {
      id: 'M-Q23',
      dimension: 'D5',
      kind: 'scale',
      stem: '你们讨论过「分手条件」吗？（什么情况下会分手）',
      options: [
        { label: 'A', text: '讨论过，我们都认为基本不会', scoring: { D5: 25 } },
        { label: 'B', text: '隐约提过，但没认真聊', scoring: { D5: 15 } },
        { label: 'C', text: '没讨论过，怕聊这个伤感情', scoring: { D5: 5 } },
        { label: 'D', text: '讨论过，她有明确底线', scoring: { D5: 20 } },
      ],
      rationale: '测未来承诺',
    },
    {
      id: 'M-Q24',
      dimension: 'funny',
      kind: 'funny',
      isFunny: true,
      stem: '如果有个超级漂亮的女生主动加你微信，你的第一反应是？',
      options: [
        { label: 'A', text: '拒绝，我有她了', scoring: { D5: 20 } },
        { label: 'B', text: '通过但立刻告诉女朋友', scoring: { D5: 18 } },
        { label: 'C', text: '通过但不告诉，纯聊天', scoring: { D5: 10 } },
        { label: 'D', text: '通过且互动，看情况发展', scoring: { D5: 5 } },
      ],
      rationale: '无厘头 · 测忠诚度',
    },
    // ==================== D6 · 亲密激情 ====================
    {
      id: 'M-Q25',
      dimension: 'D6',
      kind: 'scale',
      stem: '你们上一次主动拥抱对方，是什么时候？',
      options: [
        { label: 'A', text: '今天/昨天', scoring: { D6: 25 } },
        { label: 'B', text: '一周内', scoring: { D6: 15 } },
        { label: 'C', text: '一个月内', scoring: { D6: 5 } },
        { label: 'D', text: '记不清了', scoring: { D6: 0 } },
      ],
      rationale: '测身体亲密度',
    },
    {
      id: 'M-Q26',
      dimension: 'D6',
      kind: 'scale',
      stem: '你们对「身体亲密接触」的频率，双方期望一致吗？',
      options: [
        { label: 'A', text: '完全一致，都很满足', scoring: { D6: 25 } },
        { label: 'B', text: '大致一致，偶尔不一致', scoring: { D6: 15 } },
        { label: 'C', text: '我想要更多，她想要更少', scoring: { D6: 10 } },
        { label: 'D', text: '她想要更多，我想要更少', scoring: { D6: 10 } },
      ],
      rationale: '测亲密接触频率匹配',
    },
    {
      id: 'M-Q27',
      dimension: 'D6',
      kind: 'scale',
      stem: '关于「亲密生活的频率和质量」，你们的状态是？',
      options: [
        { label: 'A', text: '频率质量都满意', scoring: { D6: 25 } },
        { label: 'B', text: '频率满意但质量一般', scoring: { D6: 15 } },
        { label: 'C', text: '频率不满意但能沟通', scoring: { D6: 10 } },
        { label: 'D', text: '几乎不聊这个话题，各想各的', scoring: { D6: 0 } },
      ],
      rationale: '测性需求匹配度',
    },
    {
      id: 'M-Q28',
      dimension: 'D6',
      kind: 'scale',
      stem: '在一起多久了？现在看到她换衣服/刚洗完澡，你的反应是？',
      options: [
        { label: 'A', text: '还会心动', scoring: { D6: 25 } },
        { label: 'B', text: '偶尔心动，但不如以前', scoring: { D6: 15 } },
        { label: 'C', text: '习惯了，没特别感觉', scoring: { D6: 5 } },
        { label: 'D', text: '反而觉得烦', scoring: { D6: 0 } },
      ],
      rationale: '测激情延续',
    },
    {
      id: 'M-Q29',
      dimension: 'D6',
      kind: 'scale',
      stem: '当你们的「亲密需求」不一致时，怎么处理？',
      options: [
        { label: 'A', text: '直接聊，找双方都舒服的方式', scoring: { D6: 25 } },
        { label: 'B', text: '一方妥协，但心里不爽', scoring: { D6: 10 } },
        { label: 'C', text: '避而不谈，假装没问题', scoring: { D6: 5 } },
        { label: 'D', text: '因此吵架，但解决不了', scoring: { D6: 0 } },
      ],
      rationale: '测亲密沟通',
    },
  ],
};
